name = "cf-worker-intervals-test"
main = "src/index.ts"
compatibility_date = "2022-06-03"

[durable_objects]
bindings = [
  { name = "intervalsTestDO", class_name = "IntervalsTestDO" },
]

[[migrations]]
tag = "v1"
new_classes = ["IntervalsTestDO"]

